SPREADSHEET_ID = "1FS4aEcUanTG5R9XlIH4b8_t8epsZ5WxXIXvCYchln9s"
SPREADSHEET_URL = f"https://docs.google.com/spreadsheets/d/{SPREADSHEET_ID}"
POLL_SECONDS = 10
PDF_SHEET_NAME = "pdfs"
PDF_SHEET_URL = f"{SPREADSHEET_URL}/edit#gid=669753000"
